#pragma config(Sensor, dgtl1,  encoder1,        sensorQuadEncoder)
#pragma config(Motor,  port2,           motor1,         tmotorVex393_HBridge, openLoop, encoderPort, dgtl1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	resetMotorEncoder(motor1);
	int target = 10;
	int speed = 0;
	int s = 0;
	int d = 0;
	while(true) {
		s = SensorValue[encoder1];
		wait(100, milliseconds);
		d = SensorValue[encoder1] - s;
		if(d<target) {
			speed++;
		} else if(d>target) {
			speed--;
		}
		if(speed > 127 || speed < -127) {
			return;
		}
		setMotor(motor1, speed);
	}
}
